# Generated by Django 5.1.3 on 2024-11-22 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('setor', models.CharField(default='Sem setor', max_length=100)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=10)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('status', models.CharField(choices=[('a_fazer', 'A Fazer'), ('fazendo', 'Fazendo'), ('pronto', 'Pronto')], default='a_fazer', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='tarefas.usuario')),
            ],
        ),
    ]
